all: 
	$(LCXX) $(LCFLAGS) -o pop ns_pop.cpp $(LIBS)

pop:
	$(LCXX) $(LCFLAGS) -o pop ns_pop.cpp $(LIBS)

o2gen:
	$(CXX) $(LDFLAGS) -o o2gen o2script.cpp ns_pop.cpp pop_data.cpp $(LIBS)

plot:	
	gnuplot "ns_pop.gnu"
