compare_threep:
	./bamr_nompi -threads 1 -set aff_inv 0 -set couple_threads 0 \
		-set use_population 1 \
		-set min_max_mass 1.98 \
		-set prefix compare_threep_2 \
		-set max_time 86400 \
		-set n_walk 1 -set step_fac 4000.0 \
		-set norm_max 0 -set addl_quants 1 \
		-set inc_baryon_mass 1 \
		-set crust_from_L 0 -set compute_cthick 1 \
		-set file_update_time 10 -set verbose 2 \
		-set mcmc_verbose 2 -add-data-alt 6304 \
		data/shb18/6304_H_nopl_syst_wilm.o2 \
		data/shb18/6304_He_nopl_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt 6397 \
		data/shb18/6397_H_syst_wilm.o2 \
		data/shb18/6397_He_syst_wilm3.o2 \
		like 0.7 rescaled \
		-add-data-alt M13 \
		data/shs18/M13_H_rs.o2 \
		data/shs18/M13_He_rs.o2 \
		like 0.7 rescaled_0 \
		-add-data-alt M28 \
		data/shb18/M28_H_syst_wilm.o2 \
		data/shb18/M28_He_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt M30 \
		data/shb18/M30_H_syst_wilm.o2 \
		data/shb18/M30_He_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt wCen \
		data/shb18/wCen_H_syst_wilm.o2 \
		data/shb18/wCen_H_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt X7 \
		data/shb18/X7_H_syst_wilm.o2 \
		data/shb18/X7_He_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt 1810b \
		data/nks15/1810.o2 \
		data/nks15/1810.o2 \
		weights 0.7 mcarlo \
		-add-data-alt 1724b \
		data/nks15/1724.o2 \
		data/nks15/1724.o2 \
		weights 0.7 mcarlo \
		-add-data-alt 1702 \
		data/nat17/1702_D_X_int.o2 \
		data/nat17/1702_D_X_int.o2 \
		avgs 0.7 hist2_table \
		-add-data-alt 0030 \
		data/nicer/0030_st_pst.o2 \
		data/nicer/0030_st_pst.o2 \
		prob 0.7 table3d \
		-set apply_intsc 0 \
		-set cached_intsc 0 \
		-model tews_threep_ligo \
		-initial-point-last guess \
		-set prior_eta 1 \
		-set mmax_deriv 1 \
		-mcmc 
# > mcmc_threep_2.out 2>&1 &

compare_fixp:
	./bamr -threads 1 -set aff_inv 0 -set couple_threads 0 \
		-set prefix compare_fixp_2 -set max_time 172800 \
		-set n_walk 1 -set step_fac 200.0 \
		-set norm_max 0 -set addl_quants 1 -set inc_baryon_mass 1 \
		-set crust_from_L 0 -set compute_cthick 1 \
		-set file_update_time 1800 -set verbose 3 \
		-set mcmc_verbose 2 -add-data-alt 6304 \
		data/shb18/6304_H_nopl_syst_wilm.o2 \
		data/shb18/6304_He_nopl_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt 6397 \
		data/shb18/6397_H_syst_wilm.o2 \
		data/shb18/6397_He_syst_wilm3.o2 \
		like 0.7 rescaled \
		-add-data-alt M13 \
		data/shs18/M13_H_rs.o2 \
		data/shs18/M13_He_rs.o2 \
		like 0.7 rescaled_0 \
		-add-data-alt M28 \
		data/shb18/M28_H_syst_wilm.o2 \
		data/shb18/M28_He_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt M30 \
		data/shb18/M30_H_syst_wilm.o2 \
		data/shb18/M30_He_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt wCen \
		data/shb18/wCen_H_syst_wilm.o2 \
		data/shb18/wCen_H_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt X7 \
		data/shb18/X7_H_syst_wilm.o2 \
		data/shb18/X7_He_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt 1810b \
		data/nks15/1810.o2 \
		data/nks15/1810.o2 \
		weights 0.7 mcarlo \
		-add-data-alt 1724b \
		data/nks15/1724.o2 \
		data/nks15/1724.o2 \
		weights 0.7 mcarlo \
		-add-data-alt 1702 \
		data/nat17/1702_D_X_int.o2 \
		data/nat17/1702_D_X_int.o2 \
		avgs 0.7 hist2_table \
		-add-data-alt 0030 \
		data/nicer/0030_st_pst.o2 \
		data/nicer/0030_st_pst.o2 \
		prob 0.7 table3d \
		-set apply_intsc 1 \
		-set cached_intsc 1 \
		-model tews_fixp_ligo \
		-set prior_eta 1 \
		-set mmax_deriv 1 \
		-mcmc > mcmc_fixp_2.out 2>&1 &

#		acol -read compare_0_out -get-row 0 > compare.txt

test_emu_nodata:
	./bamr_nompi -threads 1 -set n_walk 50 \
		-set aff_inv 1 -set step_fac 2.0 -set max_time 43200 \
		-set prefix test_emu_nodata \
		-set norm_max 0 -set addl_quants 1 -set inc_baryon_mass 1 \
		-set crust_from_L 0 -set compute_cthick 1 \
		-set file_update_time 60 -set verbose 1 \
		-set mcmc_verbose 1 \
		-model tews_threep_ligo \
		-set apply_emu 1 \
		-set emu_train emu_test/nodata_dpde_test \
		-set prior_eta 1 \
		-mcmc 

test_emulate_post:
	./bamr_nompi -threads 1 -model tews_threep_ligo \
		-set verbose 3 -set norm_max 0 \
		-set addl_quants 1 -set inc_baryon_mass 1 \
		-set crust_from_L 0 -set compute_cthick 1 \
		-set emu_post 1 \
		-emu-points test_emu_nodata_0_out test_emu_nodata_0_post 1


test_emu:
	./bamr_nompi -threads 1 -set n_walk 50 \
		-set aff_inv 1 -set step_fac 2.0 -set max_time 864000 \
		-set prefix test_emu \
		-set norm_max 0 -set addl_quants 1 -set inc_baryon_mass 1 \
		-set crust_from_L 0 -set compute_cthick 1 \
		-set file_update_time 60 -set verbose 1 -set mcmc_verbose 1 \
		-add-data-alt 6304 \
		data/shb18/6304_H_nopl_syst_wilm.o2 \
		data/shb18/6304_He_nopl_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt 6397 \
		data/shb18/6397_H_syst_wilm.o2 \
		data/shb18/6397_He_syst_wilm3.o2 \
		like 0.7 rescaled \
		-add-data-alt M13 \
		data/shs18/M13_H_rs.o2 \
		data/shs18/M13_He_rs.o2 \
		like 0.7 rescaled_0 \
		-add-data-alt M28 \
		data/shb18/M28_H_syst_wilm.o2 \
		data/shb18/M28_He_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt M30 \
		data/shb18/M30_H_syst_wilm.o2 \
		data/shb18/M30_He_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt wCen \
		data/shb18/wCen_H_syst_wilm.o2 \
		data/shb18/wCen_H_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt X7 \
		data/shb18/X7_H_syst_wilm.o2 \
		data/shb18/X7_He_syst_wilm.o2 \
		like 0.7 rescaled \
		-add-data-alt 1810 \
		data/nks15/1810.o2 \
		data/nks15/1810.o2 \
		weights 0.7 mcarlo \
		-add-data-alt 1724 \
		data/nks15/1724.o2 \
		data/nks15/1724.o2 \
		weights 0.7 mcarlo \
		-add-data-alt 1702 \
		data/nat17/1702_D_X_int.o2 \
		data/nat17/1702_D_X_int.o2 \
		avgs 0.7 hist2_table \
		-add-data-alt 0030 \
		data/nicer/0030_st_pst.o2 \
		data/nicer/0030_st_pst.o2 \
		prob 0.7 table3d \
		-model tews_threep_ligo \
		-set apply_emu 1 -set emu_train emu_test/nicer_dpde_test \
		-set prior_eta 1 \
		-mcmc 

