all: 
	$(LCXX) $(LCFLAGS) -o like likelihood.cpp $(LIBS)

like:
	$(LCXX) $(LCFLAGS) -o like likelihood.cpp $(LIBS)

test2:
	$(LCXX) $(LCFLAGS) -o test test.cpp likelihood.cpp \
		mass_data.cpp $(LIBS)

plot:	
	gnuplot "likelihood.gnu"
